# Generated by Django 5.2 on 2025-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_notification_visibility_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher'), ('maintenance', 'Maintenance'), ('all', 'All Users')], default='all', max_length=20),
        ),
    ]
