# Generated by Django 5.2 on 2025-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
