# Generated by Django 5.2 on 2025-05-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
